# Classifying news articles with Naive Bayes

Once text data has been converted into numerical features using the natural language processing techniques discussed in the previous sections, text classification works just like any other classification task.

## Imports

In [1]:
using Pkg

In [2]:
using PyCall
using Conda

In [3]:
#Pkg.add("Glob")
#Pkg.add("TextAnalysis")
#Pkg.add("ScikitLearn")
#Pkg.add("StringEncodings")

In [4]:
using Glob
using TextAnalysis
using DataFrames
using ScikitLearn
using StringEncodings

In [5]:
using ScikitLearn: @sk_import

In [6]:
@sk_import feature_extraction.text: CountVectorizer
@sk_import naive_bayes: MultinomialNB
@sk_import metrics: accuracy_score
@sk_import metrics: confusion_matrix

PyObject <function confusion_matrix at 0x000000007F329430>

## News article classification

We start with an illustration of the Naive Bayes model for news article classification using the BBC articles that we read as before to obtain a DataFrame with 2,225 articles from 5 categories.

### Read BBC articles

In [7]:
files = Glob.glob("../data/bbc/bbc/**/*.txt")

2225-element Vector{String}:
 "..\\data\\bbc\\bbc\\business\\001.txt"
 "..\\data\\bbc\\bbc\\business\\002.txt"
 "..\\data\\bbc\\bbc\\business\\003.txt"
 "..\\data\\bbc\\bbc\\business\\004.txt"
 "..\\data\\bbc\\bbc\\business\\005.txt"
 "..\\data\\bbc\\bbc\\business\\006.txt"
 "..\\data\\bbc\\bbc\\business\\007.txt"
 "..\\data\\bbc\\bbc\\business\\008.txt"
 "..\\data\\bbc\\bbc\\business\\009.txt"
 "..\\data\\bbc\\bbc\\business\\010.txt"
 "..\\data\\bbc\\bbc\\business\\011.txt"
 "..\\data\\bbc\\bbc\\business\\012.txt"
 "..\\data\\bbc\\bbc\\business\\013.txt"
 ⋮
 "..\\data\\bbc\\bbc\\tech\\390.txt"
 "..\\data\\bbc\\bbc\\tech\\391.txt"
 "..\\data\\bbc\\bbc\\tech\\392.txt"
 "..\\data\\bbc\\bbc\\tech\\393.txt"
 "..\\data\\bbc\\bbc\\tech\\394.txt"
 "..\\data\\bbc\\bbc\\tech\\395.txt"
 "..\\data\\bbc\\bbc\\tech\\396.txt"
 "..\\data\\bbc\\bbc\\tech\\397.txt"
 "..\\data\\bbc\\bbc\\tech\\398.txt"
 "..\\data\\bbc\\bbc\\tech\\399.txt"
 "..\\data\\bbc\\bbc\\tech\\400.txt"
 "..\\data\\bbc\\bbc\\tech\\

In [8]:
doc_list = Any[]
for (i,file) in enumerate(files)
    f = open(file,"r")
    s = StringDecoder(f,"LATIN1", "UTF-8")
    topic = split(file, "\\")[end-1]
    lines = readlines(s)
    heading = strip(lines[1])
    body = strip(join([strip(line) for line in lines[2:end]]))
    push!(doc_list, [topic, heading, body])
    close(s)
    close(f)
end

In [9]:
docs = DataFrame(topic = [String(x[1]) for x in doc_list], heading = [String(x[2]) for x in doc_list], body = [String(x[3]) for x in doc_list])

2225×3 DataFrame
  Row │ topic     heading                            body                      ⋯
      │ String    String                             String                    ⋯
──────┼─────────────────────────────────────────────────────────────────────────
    1 │ business  Ad sales boost Time Warner profit  Quarterly profits at US m ⋯
    2 │ business  Dollar gains on Greenspan speech   The dollar has hit its hi
    3 │ business  Yukos unit buyer faces loan claim  The owners of embattled R
    4 │ business  High fuel prices hit BA's profits  British Airways has blame
    5 │ business  Pernod takeover talk lifts Domecq  Shares in UK drinks and f ⋯
    6 │ business  Japan narrowly escapes recession   Japan's economy teetered
    7 │ business  Jobs growth still slow in the US   The US created fewer jobs
    8 │ business  India calls for fair trade rules   India, which attends the
    9 │ business  Ethiopia's crop production up 24%  Ethiopia produced 14.27 m ⋯
   10 │ business  Court rejects $280bn tobacco case  A US government claim acc
   11 │ business  Ask Jeeves tips online ad revival  Ask Jeeves has become the
  ⋮   │    ⋮                      ⋮                                  ⋮         ⋱
 2216 │ tech      Broadband fuels online expression  Fast web access is encour
 2217 │ tech      Savvy searchers fail to spot ads   Internet search engine us ⋯
 2218 │ tech      TV's future down the phone line    Internet TV has been talk
 2219 │ tech      Cebit fever takes over Hanover     Thousands of products and
 2220 │ tech      New consoles promise big problems  Making games for future c
 2221 │ tech      BT program to beat dialler scams   BT is introducing two ini ⋯
 2222 │ tech      Spam e-mails tempt net shoppers    Computer users across the
 2223 │ tech      Be careful how you code            A new European directive
 2224 │ tech      US cyber security chief resigns    The man making sure US co
 2225 │ tech      Losing yourself in online gaming   Online role playing games ⋯
                                                  1 column and 2204 rows omitted

### Create stratified train-test split

We split the data into the default 75:25 train-test sets, ensuring that the test set classes closely mirror the train set:

In [10]:
using Random

function partitionTrainTest(data, at = 0.75)
    n = nrow(data)
    idx = shuffle(1:n)
    train_idx = view(idx, 1:floor(Int, at*n))
    test_idx = view(idx, (floor(Int, at*n)+1):n)
    data[train_idx,:], data[test_idx,:]
end

partitionTrainTest (generic function with 2 methods)

In [11]:
function get_factorized_topic(topic)
    if topic == "business"
        return 0
    elseif topic == "entertainment"
        return 1
    elseif topic == "politics"
        return 2
    elseif topic == "sport"
        return 3
    elseif topic == "tech"
        return 4
    end
end

get_factorized_topic (generic function with 1 method)

In [12]:
train, test = partitionTrainTest(docs, 0.75)

X_train = [String(substr_text) for substr_text in train.body]
X_test = [String(substr_text) for substr_text in test.body]

y_train = [get_factorized_topic(topic) for topic in train.topic]
y_test = [get_factorized_topic(topic) for topic in test.topic]

557-element Vector{Int64}:
 3
 3
 1
 3
 2
 2
 3
 1
 4
 4
 3
 1
 1
 ⋮
 0
 2
 2
 0
 0
 2
 1
 4
 3
 2
 3
 3

### Vectorize text data

We proceed to learn the vocabulary from the training set and transforming both dataset using the CountVectorizer with default settings to obtain almost 26,000 features:

In [13]:
vectorizer = CountVectorizer()
X_train_dtm = vectorizer.fit_transform(X_train)
X_test_dtm = vectorizer.transform(X_test)

PyObject <557x25917 sparse matrix of type '<class 'numpy.int64'>'
	with 109520 stored elements in Compressed Sparse Row format>

In [14]:
X_train_dtm.shape, X_test_dtm.shape

((1668, 25917), (557, 25917))

### Train Multi-class Naive Bayes model

In [15]:
classes = unique(y_train)
nbc = NaiveBayesClassifier(classes)

NaiveBayesClassifier{Int64}(String[], [3, 2, 0, 1, 4], Matrix{Int64}(undef, 0, 5))

In [16]:
for (text, class) in zip(X_train, y_train)
    TextAnalysis.fit!(nbc, text, class)
end

In [17]:
nb = MultinomialNB()
nb.fit(X_train_dtm, y_train)
y_pred_class = nb.predict(X_test_dtm)

557-element Vector{Int64}:
 3
 3
 1
 3
 2
 2
 3
 1
 4
 4
 3
 1
 1
 ⋮
 0
 2
 2
 0
 0
 2
 1
 4
 3
 2
 3
 3

### Evaluate Results

We evaluate the multiclass predictions using accuracy to find the default classifier achieved almost 98%:

#### Accuracy

In [18]:
accuracy_score(y_test, y_pred_class)

0.9766606822262118

#### Confusion matrix

In [19]:
DataFrame(confusion_matrix(y_true=y_test, y_pred=y_pred_class), :auto)

5×5 DataFrame
 Row │ x1     x2     x3     x4     x5    
     │ Int64  Int64  Int64  Int64  Int64 
─────┼───────────────────────────────────
   1 │   141      0      4      0      4
   2 │     1     97      1      0      1
   3 │     0      0     89      0      0
   4 │     1      1      0    131      0
   5 │     0      0      0      0     86